spring.application.name=journaling app
spring.data.mongodb.host=localhost 
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=//myjournaluser
#pring.data.mongodb.password=mypasswword
spring.data.mongodb.auto-index-creation=true
#it is used there where we have used the name that has to be unique.



# mongodb+srv://ashutoshsingh26362456_db_user:<db_password>@cluster0.rc59nkq.mongodb.net/?appName=Cluster0